//go:build !ignore_autogenerated

/*
Copyright 2026 The MCP Gateway Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQuota) DeepCopyInto(out *AgentQuota) {
	*out = *in
	if in.MaxConcurrentConnections != nil {
		in, out := &in.MaxConcurrentConnections, &out.MaxConcurrentConnections
		*out = new(int32)
		**out = **in
	}
	if in.MaxMonthlyToolCalls != nil {
		in, out := &in.MaxMonthlyToolCalls, &out.MaxMonthlyToolCalls
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQuota.
func (in *AgentQuota) DeepCopy() *AgentQuota {
	if in == nil {
		return nil
	}
	out := new(AgentQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRateLimits) DeepCopyInto(out *AgentRateLimits) {
	*out = *in
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(RateLimitEntry)
		**out = **in
	}
	if in.PerTool != nil {
		in, out := &in.PerTool, &out.PerTool
		*out = make([]ToolRateLimitEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRateLimits.
func (in *AgentRateLimits) DeepCopy() *AgentRateLimits {
	if in == nil {
		return nil
	}
	out := new(AgentRateLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPolicy) DeepCopyInto(out *DefaultPolicy) {
	*out = *in
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedTools != nil {
		in, out := &in.DeniedTools, &out.DeniedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPolicy.
func (in *DefaultPolicy) DeepCopy() *DefaultPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredCapabilities) DeepCopyInto(out *DiscoveredCapabilities) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prompts != nil {
		in, out := &in.Prompts, &out.Prompts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastDiscoveredAt != nil {
		in, out := &in.LastDiscoveredAt, &out.LastDiscoveredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredCapabilities.
func (in *DiscoveredCapabilities) DeepCopy() *DiscoveredCapabilities {
	if in == nil {
		return nil
	}
	out := new(DiscoveredCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallTemplate) DeepCopyInto(out *InstallTemplate) {
	*out = *in
	in.MCPServerSpec.DeepCopyInto(&out.MCPServerSpec)
	if in.RequiredSecrets != nil {
		in, out := &in.RequiredSecrets, &out.RequiredSecrets
		*out = make([]RequiredSecret, len(*in))
		copy(*out, *in)
	}
	if in.DefaultPolicy != nil {
		in, out := &in.DefaultPolicy, &out.DefaultPolicy
		*out = new(DefaultPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallTemplate.
func (in *InstallTemplate) DeepCopy() *InstallTemplate {
	if in == nil {
		return nil
	}
	out := new(InstallTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAgent) DeepCopyInto(out *MCPAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAgent.
func (in *MCPAgent) DeepCopy() *MCPAgent {
	if in == nil {
		return nil
	}
	out := new(MCPAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAgentIdentity) DeepCopyInto(out *MCPAgentIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAgentIdentity.
func (in *MCPAgentIdentity) DeepCopy() *MCPAgentIdentity {
	if in == nil {
		return nil
	}
	out := new(MCPAgentIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAgentList) DeepCopyInto(out *MCPAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAgentList.
func (in *MCPAgentList) DeepCopy() *MCPAgentList {
	if in == nil {
		return nil
	}
	out := new(MCPAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAgentSpec) DeepCopyInto(out *MCPAgentSpec) {
	*out = *in
	out.Identity = in.Identity
	if in.ServerAccess != nil {
		in, out := &in.ServerAccess, &out.ServerAccess
		*out = make([]ServerAccessEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(AgentRateLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(AgentQuota)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAgentSpec.
func (in *MCPAgentSpec) DeepCopy() *MCPAgentSpec {
	if in == nil {
		return nil
	}
	out := new(MCPAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAgentStatus) DeepCopyInto(out *MCPAgentStatus) {
	*out = *in
	if in.RegisteredAt != nil {
		in, out := &in.RegisteredAt, &out.RegisteredAt
		*out = (*in).DeepCopy()
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAgentStatus.
func (in *MCPAgentStatus) DeepCopy() *MCPAgentStatus {
	if in == nil {
		return nil
	}
	out := new(MCPAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPMarketplaceEntry) DeepCopyInto(out *MCPMarketplaceEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPMarketplaceEntry.
func (in *MCPMarketplaceEntry) DeepCopy() *MCPMarketplaceEntry {
	if in == nil {
		return nil
	}
	out := new(MCPMarketplaceEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPMarketplaceEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPMarketplaceEntryList) DeepCopyInto(out *MCPMarketplaceEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPMarketplaceEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPMarketplaceEntryList.
func (in *MCPMarketplaceEntryList) DeepCopy() *MCPMarketplaceEntryList {
	if in == nil {
		return nil
	}
	out := new(MCPMarketplaceEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPMarketplaceEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPMarketplaceEntrySpec) DeepCopyInto(out *MCPMarketplaceEntrySpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Source = in.Source
	in.InstallTemplate.DeepCopyInto(&out.InstallTemplate)
	in.Security.DeepCopyInto(&out.Security)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPMarketplaceEntrySpec.
func (in *MCPMarketplaceEntrySpec) DeepCopy() *MCPMarketplaceEntrySpec {
	if in == nil {
		return nil
	}
	out := new(MCPMarketplaceEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPMarketplaceEntryStatus) DeepCopyInto(out *MCPMarketplaceEntryStatus) {
	*out = *in
	if in.LastInstalledAt != nil {
		in, out := &in.LastInstalledAt, &out.LastInstalledAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPMarketplaceEntryStatus.
func (in *MCPMarketplaceEntryStatus) DeepCopy() *MCPMarketplaceEntryStatus {
	if in == nil {
		return nil
	}
	out := new(MCPMarketplaceEntryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicy) DeepCopyInto(out *MCPPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicy.
func (in *MCPPolicy) DeepCopy() *MCPPolicy {
	if in == nil {
		return nil
	}
	out := new(MCPPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicyList) DeepCopyInto(out *MCPPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicyList.
func (in *MCPPolicyList) DeepCopy() *MCPPolicyList {
	if in == nil {
		return nil
	}
	out := new(MCPPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicySpec) DeepCopyInto(out *MCPPolicySpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicySpec.
func (in *MCPPolicySpec) DeepCopy() *MCPPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MCPPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicyStatus) DeepCopyInto(out *MCPPolicyStatus) {
	*out = *in
	if in.SyncedAt != nil {
		in, out := &in.SyncedAt, &out.SyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicyStatus.
func (in *MCPPolicyStatus) DeepCopy() *MCPPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MCPPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServer) DeepCopyInto(out *MCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServer.
func (in *MCPServer) DeepCopy() *MCPServer {
	if in == nil {
		return nil
	}
	out := new(MCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerHealthCheck) DeepCopyInto(out *MCPServerHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerHealthCheck.
func (in *MCPServerHealthCheck) DeepCopy() *MCPServerHealthCheck {
	if in == nil {
		return nil
	}
	out := new(MCPServerHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerList) DeepCopyInto(out *MCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerList.
func (in *MCPServerList) DeepCopy() *MCPServerList {
	if in == nil {
		return nil
	}
	out := new(MCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerProtocol) DeepCopyInto(out *MCPServerProtocol) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerProtocol.
func (in *MCPServerProtocol) DeepCopy() *MCPServerProtocol {
	if in == nil {
		return nil
	}
	out := new(MCPServerProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerScaling) DeepCopyInto(out *MCPServerScaling) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.ScaleToZero != nil {
		in, out := &in.ScaleToZero, &out.ScaleToZero
		*out = new(ScaleToZeroConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerScaling.
func (in *MCPServerScaling) DeepCopy() *MCPServerScaling {
	if in == nil {
		return nil
	}
	out := new(MCPServerScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSecret) DeepCopyInto(out *MCPServerSecret) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSecret.
func (in *MCPServerSecret) DeepCopy() *MCPServerSecret {
	if in == nil {
		return nil
	}
	out := new(MCPServerSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSource) DeepCopyInto(out *MCPServerSource) {
	*out = *in
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(MCPServerHealthCheck)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSource.
func (in *MCPServerSource) DeepCopy() *MCPServerSource {
	if in == nil {
		return nil
	}
	out := new(MCPServerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.Protocol = in.Protocol
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(MCPServerScaling)
		(*in).DeepCopyInto(*out)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]MCPServerSecret, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerStatus) DeepCopyInto(out *MCPServerStatus) {
	*out = *in
	if in.DiscoveredCapabilities != nil {
		in, out := &in.DiscoveredCapabilities, &out.DiscoveredCapabilities
		*out = new(DiscoveredCapabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerStatus.
func (in *MCPServerStatus) DeepCopy() *MCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceSource) DeepCopyInto(out *MarketplaceSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceSource.
func (in *MarketplaceSource) DeepCopy() *MarketplaceSource {
	if in == nil {
		return nil
	}
	out := new(MarketplaceSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPrincipals) DeepCopyInto(out *PolicyPrincipals) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentRefs != nil {
		in, out := &in.AgentRefs, &out.AgentRefs
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPrincipals.
func (in *PolicyPrincipals) DeepCopy() *PolicyPrincipals {
	if in == nil {
		return nil
	}
	out := new(PolicyPrincipals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyResources) DeepCopyInto(out *PolicyResources) {
	*out = *in
	if in.ServerRef != nil {
		in, out := &in.ServerRef, &out.ServerRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyResources.
func (in *PolicyResources) DeepCopy() *PolicyResources {
	if in == nil {
		return nil
	}
	out := new(PolicyResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	in.Principals.DeepCopyInto(&out.Principals)
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRule.
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitEntry) DeepCopyInto(out *RateLimitEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitEntry.
func (in *RateLimitEntry) DeepCopy() *RateLimitEntry {
	if in == nil {
		return nil
	}
	out := new(RateLimitEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredSecret) DeepCopyInto(out *RequiredSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredSecret.
func (in *RequiredSecret) DeepCopy() *RequiredSecret {
	if in == nil {
		return nil
	}
	out := new(RequiredSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleToZeroConfig) DeepCopyInto(out *ScaleToZeroConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleToZeroConfig.
func (in *ScaleToZeroConfig) DeepCopy() *ScaleToZeroConfig {
	if in == nil {
		return nil
	}
	out := new(ScaleToZeroConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityInfo) DeepCopyInto(out *SecurityInfo) {
	*out = *in
	if in.LastScannedAt != nil {
		in, out := &in.LastScannedAt, &out.LastScannedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityInfo.
func (in *SecurityInfo) DeepCopy() *SecurityInfo {
	if in == nil {
		return nil
	}
	out := new(SecurityInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerAccessEntry) DeepCopyInto(out *ServerAccessEntry) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerAccessEntry.
func (in *ServerAccessEntry) DeepCopy() *ServerAccessEntry {
	if in == nil {
		return nil
	}
	out := new(ServerAccessEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolRateLimitEntry) DeepCopyInto(out *ToolRateLimitEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolRateLimitEntry.
func (in *ToolRateLimitEntry) DeepCopy() *ToolRateLimitEntry {
	if in == nil {
		return nil
	}
	out := new(ToolRateLimitEntry)
	in.DeepCopyInto(out)
	return out
}
